version: '3.9'

services:
  # flaskのpython環境
  flask:
    # 管理コンテナ名
    container_name: ${APP_NAME}-app
    # Dockerファイルにて 定義
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    # マウント
    volumes:
      - ./app:/usr/src/app
      - ./docker/python/.env.dev:/usr/src/app/.env
      - ./ssh/docker_ssh_id_rsa:/root/.ssh/docker_ssh_id_rsa
      - ./docker/python/ssh_config:/root/.ssh/config
    # PORT = for flask
    ports:
      - ${WEB_PORT}:5000
    # flask起動させる 「--debugger --reload」でのホットリロード(開発用)
    command: flask run --host=0.0.0.0 --debugger --reload
  # フロントエンド(別サーバーで管理 前提)
  front:
    # 管理コンテナ名
    container_name: ${APP_NAME}-front
    # Dockerファイルにて定義
    build:
        context: .
        dockerfile: ./docker/vite/Dockerfile
    # 場所
    volumes:
      - ./front:/var/www/html
      - ./docker/vite/.env.dev:/var/www/html/.env
    # PORT = for watch
    ports:
      - ${FRONT_PORT:-3000}:5173
    # ホットリロード(開発用)で起動
    command: yarn run dev
    # コンテナを正常終了するのを防ぐ
    tty: true
  # SSH接続先用
  ssh_server:
    # 管理コンテナ名
    container_name: ${APP_NAME}-ssh
    # host名
    hostname: ssh_server
    # Dockerファイルにて定義
    build:
        context: .
        dockerfile: ./docker/ssh_server/Dockerfile
    # マウント
    volumes:
      - ./ssh:/root/.ssh
      - ./script:/root/test
    # root実行の権限許可
    privileged: true
    command: /sbin/init
    # 利用ポート: カスタムSSH固定(ホスト側は特に使っていないから一緒にしているだけ)
    ports:
      - "20022:20022"