version: '3.8'

services:
  # flaskのpython環境
  flask:
    # 管理コンテナ名
    container_name: ${APP_NAME}-app
    # Dockerファイルにて 定義
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    # マウント
    volumes:
      - ./app:/usr/src/app
    # 利用ポート
    ports:
      - ${WEB_PORT}:5000
    # flask起動させる 「--debugger --reload」でのホットリロード(開発用)
    command: flask run --host=0.0.0.0 --debugger --reload